[package]
name = "robin_d7_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
rand = "0.8"
serde_json = "1.0"
z_rr = { path = "../z_rr" }
