[package]
name = "millennium_watch"
version = "0.1.0"
edition = "2024"

[dependencies]
z_rr = { path = "../z_rr" }
robin_d7_rust = { path = "../robin_d7_rust" }

[[bin]]
name = "millennium_watch"
path = "src/main.rs"

[[bin]]
name = "law_cache"
path = "src/law_cache.rs"

