[package]
name = "zrr_core"
version = "0.1.0"
edition = "2021"

[dependencies]
zip = "0.6"
rand = "0.8"
memmap2 = "0.9"
crc32fast = "1.3"
walkdir = "2"
chrono = "0.4"
ndarray = "0.15"  # For Talu64 matrix operations
ndarray-npy = "0.8" # To load AlphaTensor .npz files if needed
